# Generated by Django 2.1.15 on 2021-03-23 05:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('middlename', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('emailAddress', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('birthdate', models.DateField(blank=True, default=datetime.datetime(2021, 3, 23, 13, 40, 7, 31397), null=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('requestID', models.AutoField(primary_key=True, serialize=False)),
                ('isApprove', models.IntegerField()),
                ('user', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='userID', to='User.User')),
            ],
            options={
                'db_table': 'UserRequest',
            },
        ),
    ]
