# Generated by Django 2.1.15 on 2021-03-21 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2021, 3, 21, 20, 33, 28, 385032)),
        ),
    ]
