# Generated by Django 2.1.15 on 2021-03-21 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20210321_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 21, 20, 34, 30, 768618), null=True),
        ),
    ]
