# Generated by Django 2.1.15 on 2021-03-21 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20210321_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 21, 21, 23, 57, 131019), null=True),
        ),
    ]
