# Generated by Django 2.1.15 on 2021-03-25 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20210326_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isCancelled',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notificationDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 26, 1, 58, 42, 51131), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 26, 1, 58, 42, 49136), null=True),
        ),
    ]
