# Generated by Django 2.1.15 on 2021-03-23 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin', models.IntegerField(default='default', primary_key=True, serialize=False)),
                ('user', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='User', to='User.User')),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
    ]
