# Generated by Django 2.1.15 on 2021-03-22 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0006_auto_20210322_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uesrID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to='User.User')),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
    ]
