# Generated by Django 2.1.15 on 2021-03-24 03:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20210323_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventID', models.AutoField(primary_key=True, serialize=False)),
                ('eventName', models.CharField(blank=True, max_length=50, null=True)),
                ('eventDate', models.CharField(blank=True, max_length=50, null=True)),
                ('eventParticipants', models.IntegerField()),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgID', to='User.Organizer')),
            ],
            options={
                'db_table': 'Event',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 24, 11, 19, 34, 487232), null=True),
        ),
    ]
