# Generated by Django 2.1.15 on 2021-03-24 06:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20210324_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('participantsID', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventIDs', to='User.Event')),
            ],
            options={
                'db_table': 'Participants',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 24, 14, 12, 0, 921125), null=True),
        ),
        migrations.AddField(
            model_name='participants',
            name='user',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='participantUser', to='User.User'),
        ),
    ]
